const MAX_EXAM_ATTEMPT_WITH_FREE_ACCOUNT = 5;
const MAX_EXAM_ATTEMPT_WITH_PREMIUM_ACCOUNT = "UNLIMITED";

const EXAM_QUESTION_TYPE = {
  MCQ: "MCQ",
  ARRANGE: "ARRANGE",
};

export {
  MAX_EXAM_ATTEMPT_WITH_FREE_ACCOUNT,
  MAX_EXAM_ATTEMPT_WITH_PREMIUM_ACCOUNT,
  EXAM_QUESTION_TYPE,
};
